 .PHONY: all clean

 all:	more01.c more02.c more03.c more04.c


more01:more01.c
	gcc -o more01 more01.c
more02:more02.c
	gcc -o more02 more02.c
more03:more03.c
	gcc -o more03 more03.c

clean:	
	rm -f  more01 more02 more03